import fs from 'fs-extra';
import path from 'path';
import logger, { logOperation } from '../utils/logger.js';

/**
 * Install Git hooks
 */
export async function installGitHooks(): Promise<void> {
  return logOperation('Install Git Hooks', async () => {
    const gitHooksDir = path.join(process.cwd(), '.git', 'hooks');
    
    // Check if .git directory exists
    const gitDirExists = await fs.pathExists(path.join(process.cwd(), '.git'));
    if (!gitDirExists) {
      throw new Error('Not a git repository. Please run this command in a git repository.');
    }

    // Check if hooks directory exists
    const hooksExist = await fs.pathExists(gitHooksDir);
    if (!hooksExist) {
      logger.info(`Creating git hooks directory: ${gitHooksDir}`);
      await fs.mkdir(gitHooksDir, { recursive: true });
    }

    // Create pre-commit hook
    const preCommitPath = path.join(gitHooksDir, 'pre-commit');
    const preCommitContent = `#!/bin/sh
# Generated by changelog-generator

# Run the changelog generator
pnpm exec changelog-generator

# Add the generated changelog to the commit
git add docs/changelogs/

# Exit with success
exit 0
`;

    await fs.writeFile(preCommitPath, preCommitContent, 'utf8');
    
    // Make the pre-commit hook executable
    await fs.chmod(preCommitPath, '755');
    
    logger.info(`Git pre-commit hook installed at: ${preCommitPath}`);

    // Create pre-push hook if needed
    // This is optional and could be used for additional functionality
    
    logger.info('Git hooks installed successfully');
  });
}
